//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vsb.UrgentApp.Infrastructure.Db {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UrgentAppQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UrgentAppQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vsb.UrgentApp.Infrastructure.Db.UrgentAppQueries", typeof(UrgentAppQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Patient(Id, Tag_Id,Card_Id,SocialSecurityNumber,FirstName,MiddleName,LastName,BirthDate,Deleted) VALUES ({0},&apos;{1}&apos;,&apos;{2}&apos;);.
        /// </summary>
        public static string PATIENT_INSERT {
            get {
                return ResourceManager.GetString("PATIENT_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Patient;.
        /// </summary>
        public static string PATIENT_SELECT {
            get {
                return ResourceManager.GetString("PATIENT_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Tag WHERE Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAG_SELECT_BYID {
            get {
                return ResourceManager.GetString("TAG_SELECT_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagEventType WHERE Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAGEVENTTYPE_SELECT_BYID {
            get {
                return ResourceManager.GetString("TAGEVENTTYPE_SELECT_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TagRegistration WHERE Patient_Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAGREGISTRATION_DELETE_BYPATIENTID {
            get {
                return ResourceManager.GetString("TAGREGISTRATION_DELETE_BYPATIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TagRegistration(Id, Tag_Id,Patient_Id) VALUES ({0},&apos;{1}&apos;,&apos;{2}&apos;);.
        /// </summary>
        public static string TAGREGISTRATION_INSERT {
            get {
                return ResourceManager.GetString("TAGREGISTRATION_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagRegistration;.
        /// </summary>
        public static string TAGREGISTRATION_SELECT {
            get {
                return ResourceManager.GetString("TAGREGISTRATION_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT FROM TagRegistration WHERE Patient_Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAGREGISTRATION_SELECT_BYPATIENTID {
            get {
                return ResourceManager.GetString("TAGREGISTRATION_SELECT_BYPATIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TagRegistration WHERE Tag_Id = &apos;{0}&apos;;.
        /// </summary>
        public static string TAGREGISTRATION_SELECT_BYTAGID {
            get {
                return ResourceManager.GetString("TAGREGISTRATION_SELECT_BYTAGID", resourceCulture);
            }
        }
    }
}
